services:
  mysql:
    image: mysql:latest
    container_name: mi-mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - mi-mysql-vol:/var/lib/mysql
    networks:
      - mi-mysqlred

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: mi-dashboard
    environment:
      PMA_HOST: mi-mysql
    ports:
      - "8083:80"
    depends_on:
      - mysql
    networks:
      - mi-mysqlred

volumes:
  mi-mysql-vol:

networks:
  mi-mysqlred:
    ipam:
      config:
        - subnet: 172.26.0.0/16
